version: "3.8"
name: mongodb_api
services:
  #API service 
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: api
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3001:3000"
    command: npm run dev
    depends_on:
      - mongodb

  #Database Service
  mongodb:
    container_name: mongodb_server
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD={MONGODB_PASSWORD}
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
