name: Continuous Deployment
on:
  push:
    branches:
      - prod

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Restart PM2
        run: pm2 reload pm2-config.yml
